#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr> Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
my $on_off;
my $acpi_ac;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

open (ACPI_AC, "acpi -a | grep 'Adapter 0' |") or die;
$acpi_ac = <ACPI_AC>;
close(ACPI_AC);

# fail on unexpected output
if ($acpi !~ /: \w+, (\d+)%/) {
	die "$acpi\n";
}

$percent = $1;

if ($acpi_ac !~ /: (\w+)-\w+/) {
    die "$acpi_ac\n";
}
$on_off = $1;

$full_text = "$percent%";

if ($on_off eq "on") {
    $full_text = "\x{f1e6} $full_text";
} else {
    $full_text = "\x{f240} $full_text";
}
$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($on_off eq 'off') {

	if ($percent < 20) {
		print "#FF0000\n";
	} elsif ($percent < 40) {
		print "#FFAE00\n";
	} elsif ($percent < 60) {
		print "#FFF600\n";
	} elsif ($percent < 85) {
		print "#A8FF00\n";
	}

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
